input_schema_version = 2
input_poll_hz = 1000
input_mode = 'Keyboard'
gameplay_input_style = 'Arcade'
axis_press_threshold_percent = 50
axis_release_threshold_percent = 40

[keyboard]
left_booster_up = 'sc:0011'
left_booster_down = 'sc:001f'
left_booster_left = 'sc:001e'
left_booster_right = 'sc:0020'
left_booster_button = 'sc:0039'
right_booster_up = 'e0:0048'
right_booster_down = 'e0:0050'
right_booster_left = 'e0:004b'
right_booster_right = 'e0:004d'
right_booster_button = 'sc:0025'
test = 'sc:0014'
service1 = 'sc:003b'
service2 = 'sc:0017'
service3 = 'sc:0019'
p1_start = 'sc:0002'
p2_start = 'sc:0003'
p2_service = 'sc:003c'
card_read = 'sc:003e'

[controller]
backend = 'XInput'
device_id = '0'
bindings = [
  { action = 'LeftBoosterUp', type = 'XInputButton', control = 'DPadUp' },
  { action = 'LeftBoosterUp', type = 'XInputAxis', control = 'LeftY', direction = 'Negative' },
  { action = 'LeftBoosterDown', type = 'XInputButton', control = 'DPadDown' },
  { action = 'LeftBoosterDown', type = 'XInputAxis', control = 'LeftY', direction = 'Positive' },
  { action = 'LeftBoosterLeft', type = 'XInputButton', control = 'DPadLeft' },
  { action = 'LeftBoosterLeft', type = 'XInputAxis', control = 'LeftX', direction = 'Negative' },
  { action = 'LeftBoosterRight', type = 'XInputButton', control = 'DPadRight' },
  { action = 'LeftBoosterRight', type = 'XInputAxis', control = 'LeftX', direction = 'Positive' },
  { action = 'LeftBoosterButton', type = 'XInputButton', control = 'A' },
  { action = 'RightBoosterUp', type = 'XInputAxis', control = 'RightY', direction = 'Negative' },
  { action = 'RightBoosterDown', type = 'XInputAxis', control = 'RightY', direction = 'Positive' },
  { action = 'RightBoosterLeft', type = 'XInputAxis', control = 'RightX', direction = 'Negative' },
  { action = 'RightBoosterRight', type = 'XInputAxis', control = 'RightX', direction = 'Positive' },
  { action = 'RightBoosterButton', type = 'XInputButton', control = 'B' },
]

[nesys]
server_ip = '127.0.0.1'

[registry]
enabled = false
system_path = 'D:\system'

[registry.game]
country = 'GrooveCoasterJpn'

[registry.nesys]
game_kind = 303801
event_next_time = 900
condition_time = 300
log_level = 3

[logging]
level = 'Info'

[experimental]
target_fps = 60
enable_absolute_time_judgement = false
enable_testmode_storage_redirect = false
enable_timer_freeze_patches = false
unlock_all_songs_and_difficulties = false
enable_nesys_service_adapter_patch = true
audio_backend = 'directsound'
wasapi_exclusive_buffer_ms = 10
asio_driver_name = ''
asio_buffer_frames = 0
asio_output_base_channel = 0
