axis_threshold = 16384
gamepad_index = 0
input_poll_hz = 1000
input_mode = 'Keyboard'
gameplay_input_style = 'Arcade'

[gamepad]
p1_axis_horizontal = 'leftx'
p1_axis_vertical = 'lefty'
p1_button1 = 'south'
p1_dpad_down = 'dpad_left'
p1_dpad_left = 'invalid'
p1_dpad_right = 'invalid'
p1_dpad_up = 'dpad_up'
p2_axis_horizontal = 'rightx'
p2_axis_vertical = 'righty'
p2_button1 = 'east'
p2_button_down = 'dpad_right'
p2_button_left = 'invalid'
p2_button_right = 'invalid'
p2_button_up = 'dpad_down'

[keyboard]
p1_button1 = 'space'
p1_down = 'a'
p1_left = 'up'
p1_right = 'left'
p1_start = '1'
p1_up = 'w'
p2_button1 = 'k'
p2_down = 'd'
p2_left = 'down'
p2_right = 'right'
p2_service = 'f2'
p2_start = '2'
p2_up = 's'
service1 = 'f1'
service2 = 'i'
service3 = 'p'
test = 't'
card_read = 'f4'

[nesys]
server_ip = '127.0.0.1'

[registry]
enabled = false

[registry.game]
country = 'GrooveCoasterJpn'

[registry.nesys]
game_kind = 303801
event_next_time = 900
condition_time = 300
log_level = 3
news_path = 'D:\system\DUA\news'
event_path = 'D:\system\DUA\event'
log_path = 'D:\system\CmdFile\log'

[experimental]
enable_120fps_timer_patches = false
enable_testmode_storage_redirect = false
enable_timer_freeze_patches = false
enable_nesys_service_adapter_patch = true
enable_wasapi_exclusive_audio = false
wasapi_exclusive_buffer_ms = 10
