add_subdirectory(Audio)
add_subdirectory(Config)
add_subdirectory(Diagnostics)
add_subdirectory(Font)
add_subdirectory(Input)
add_subdirectory(Logging)
add_subdirectory(Nesys)
add_subdirectory(Patches)
add_subdirectory(Rfid)
add_subdirectory(SystemPath)
add_subdirectory(TestModeStorage)
add_subdirectory(Win32Hooks)
